CREATE DATABASE IF NOT EXISTS CURATED_DB;
CREATE SCHEMA IF NOT EXISTS CURATED_DB.CORE;

-- CUSTOMERS
CREATE OR REPLACE TABLE CURATED_DB.CORE.CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    COUNTRY,
    SIGNUP_DATE,
    STATUS,
    LOAD_TS
FROM RAW_DB.STAGE.CUSTOMERS_RAW;

-- ORDERS
CREATE OR REPLACE TABLE CURATED_DB.CORE.ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    ORDER_AMOUNT,
    ORDER_STATUS,
    LOAD_TS
FROM RAW_DB.STAGE.ORDERS_RAW;
