CREATE DATABASE IF NOT EXISTS CURATED_DB;
CREATE SCHEMA IF NOT EXISTS CURATED_DB.CORE;

-- Customers (rename NAME → CUSTOMER_NAME here)
CREATE OR REPLACE TABLE CURATED_DB.CORE.CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    NAME AS CUSTOMER_NAME,
    EMAIL,
    CREATED_AT
FROM RAW_DB.STAGE.CUSTOMERS_RAW;

-- Orders
CREATE OR REPLACE TABLE CURATED_DB.CORE.ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_AMOUNT,
    ORDER_DATE
FROM RAW_DB.STAGE.ORDERS_RAW;
