CREATE DATABASE IF NOT EXISTS CURATED_DB;
CREATE SCHEMA IF NOT EXISTS CURATED_DB.MART;

CREATE OR REPLACE TABLE CURATED_DB.MART.CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    COUNTRY,
    SIGNUP_DATE,
    STATUS
FROM RAW_DB.STAGE.CUSTOMERS_RAW;

CREATE OR REPLACE TABLE CURATED_DB.MART.ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    AMOUNT,
    STATUS
FROM RAW_DB.STAGE.ORDERS_RAW;
