CREATE DATABASE IF NOT EXISTS PUBLISH_DB;
CREATE SCHEMA IF NOT EXISTS PUBLISH_DB.MARTS;

CREATE OR REPLACE TABLE PUBLISH_DB.MARTS.CUSTOMER_ORDER_SUMMARY AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    COUNT(o.ORDER_ID)        AS TOTAL_ORDERS,
    COALESCE(SUM(o.ORDER_AMOUNT), 0) AS TOTAL_ORDER_AMOUNT
FROM CURATED_DB.CORE.CUSTOMERS c
LEFT JOIN CURATED_DB.CORE.ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME;
