CREATE DATABASE IF NOT EXISTS PUBLISH_DB;
CREATE SCHEMA IF NOT EXISTS PUBLISH_DB.REPORTING;

CREATE OR REPLACE VIEW PUBLISH_DB.REPORTING.CUSTOMER_ORDERS AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.COUNTRY,
    o.ORDER_ID,
    o.ORDER_DATE,
    o.AMOUNT
FROM CURATED_DB.MART.CUSTOMERS c
LEFT JOIN CURATED_DB.MART.ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID;
