CREATE DATABASE IF NOT EXISTS PUBLISH_DB;
CREATE SCHEMA IF NOT EXISTS PUBLISH_DB.MART;

CREATE OR REPLACE TABLE PUBLISH_DB.MART.CUSTOMER_ORDERS AS
SELECT
    o.ORDER_ID,
    o.ORDER_DATE,
    o.ORDER_AMOUNT,
    o.ORDER_STATUS,
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.EMAIL,
    c.COUNTRY
FROM CURATED_DB.CORE.ORDERS o
JOIN CURATED_DB.CORE.CUSTOMERS c
    ON o.CUSTOMER_ID = c.CUSTOMER_ID;
