CREATE DATABASE IF NOT EXISTS RAW_DB;
CREATE SCHEMA IF NOT EXISTS RAW_DB.STAGE;

CREATE TABLE IF NOT EXISTS RAW_DB.STAGE.CUSTOMERS_RAW (
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    CREATED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RAW_DB.STAGE.ORDERS_RAW (
    ORDER_ID INTEGER,
    CUSTOMER_ID INTEGER,
    ORDER_AMOUNT NUMBER(10,2),
    ORDER_DATE DATE
);
