CREATE DATABASE IF NOT EXISTS RAW_DB;
CREATE SCHEMA IF NOT EXISTS RAW_DB.STAGE;

CREATE OR REPLACE TABLE RAW_DB.STAGE.CUSTOMERS_RAW (
    CUSTOMER_ID NUMBER,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    COUNTRY STRING,
    SIGNUP_DATE DATE,
    STATUS STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE RAW_DB.STAGE.ORDERS_RAW (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    AMOUNT NUMBER,
    STATUS STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);
